config/routes.rb
Rails.application.routes.draw do
  resources :admins
  resources :users
  get "pages/home"
  resources :dogs
  resources :cats
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cat.rb
class Cat < ApplicationRecord
end

app/models/dog.rb
class Dog < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  has_secure_password

  ##### Validations #####
  ## -Admin data validations. Note that admin users
  ## -are required to have a unique email AND phone
  ## -number.
  validate :name, presence: true
  validate :email, presence: true, uniqueness: true
  validate :phone, presence: true, uniqueness: true
  validate :password_digest, presence: true, uniqueness: true
  #####

  ##### Admin Views #####
  ## -Views for admins.
  def admin_dashboard
  end

  def admin_profile
  end

  def stats
  end

  def inspector
    # -The inspector will be a tool
    # -for admins to search for users.
    # -It's how they access the user
    # -viewer page.
  end

  def user_viewer
    # -A detailed 'viewer' page for an admin
    # -to see certain user details.
  end
  #####
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: %i[ show edit update destroy ]

  # GET /cats or /cats.json
  def index
    @cats = Cat.all
  end

  # GET /cats/1 or /cats/1.json
  def show
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats or /cats.json
  def create
    @cat = Cat.new(cat_params)

    respond_to do |format|
      if @cat.save
        format.html { redirect_to @cat, notice: "Cat was successfully created." }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1 or /cats/1.json
  def update
    respond_to do |format|
      if @cat.update(cat_params)
        format.html { redirect_to @cat, notice: "Cat was successfully updated." }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1 or /cats/1.json
  def destroy
    @cat.destroy!

    respond_to do |format|
      format.html { redirect_to cats_path, status: :see_other, notice: "Cat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def cat_params
      params.expect(cat: [ :name, :breed, :age, :price, :description, :image_url ])
    end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: %i[ show edit update destroy ]

  # GET /dogs or /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1 or /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs or /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: "Dog was successfully created." }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1 or /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: "Dog was successfully updated." }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1 or /dogs/1.json
  def destroy
    @dog.destroy!

    respond_to do |format|
      format.html { redirect_to dogs_path, status: :see_other, notice: "Dog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def dog_params
      params.expect(dog: [ :name, :breed, :age, :price, :description, :image_url ])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact_us
  end

  def about_us
  end

  def pet_focus
  end

  def checkout
  end

  def pet_dashboard
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  has_secure_password

  ##### Validations #####
  ## -This data is required and must satisfy the
  ## -associated validations defined.
  validate :name, presence: true
  validate :email, presence: true, uniqueness: true
  validate :password_digest, presence: true, uniqueness: true
  #####

  ##### User Views #####
  ## -These are the main html views that the sites
  ## -users will work with. Rails implicitly knows
  ## -that each method renders the corresponding
  ## -html file. (e.g. bookmarks => bookmarks.html.erb)
  def user_dashboard
  end

  def user_profile
  end

  def list_a_pet
    # -Users will be able to list a pet for sale.
  end

  def bookmarks
    # -Users will be able to 'bookmark' a pet or pets.
    # -These pets can be then viewed later in a dedicated
    # -dashboard (see Pages controller).
  end
  #####
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cats/_cat.html.erb
<div id="<%= dom_id cat %>">
  <p>
    <strong>Name:</strong>
    <%= cat.name %>
  </p>

  <p>
    <strong>Breed:</strong>
    <%= cat.breed %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= cat.age %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= cat.price %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= cat.description %>
  </p>

  <p>
    <strong>Image url:</strong>
    <%= cat.image_url %>
  </p>

</div>

app/views/cats/_form.html.erb
<%= form_with(model: cat) do |form| %>
  <% if cat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
        <% cat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :breed, style: "display: block" %>
    <%= form.text_field :breed %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.label :image_url, style: "display: block" %>
    <%= form.text_field :image_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cats/edit.html.erb
<% content_for :title, "Editing cat" %>

<h1>Editing cat</h1>

<%= render "form", cat: @cat %>

<br>

<div>
  <%= link_to "Show this cat", @cat %> |
  <%= link_to "Back to cats", cats_path %>
</div>

app/views/cats/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Cats" %>

<h1>Cats</h1>

<div id="cats">
  <% @cats.each do |cat| %>
    <%= render cat %>
    <p>
      <%= link_to "Show this cat", cat %>
    </p>
  <% end %>
</div>

<%= link_to "New cat", new_cat_path %>

app/views/cats/new.html.erb
<% content_for :title, "New cat" %>

<h1>New cat</h1>

<%= render "form", cat: @cat %>

<br>

<div>
  <%= link_to "Back to cats", cats_path %>
</div>

app/views/cats/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cat %>

<div>
  <%= link_to "Edit this cat", edit_cat_path(@cat) %> |
  <%= link_to "Back to cats", cats_path %>

  <%= button_to "Destroy this cat", @cat, method: :delete %>
</div>

app/views/dogs/_dog.html.erb
<div id="<%= dom_id dog %>">
  <p>
    <strong>Name:</strong>
    <%= dog.name %>
  </p>

  <p>
    <strong>Breed:</strong>
    <%= dog.breed %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= dog.age %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= dog.price %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= dog.description %>
  </p>

  <p>
    <strong>Image url:</strong>
    <%= dog.image_url %>
  </p>

</div>

app/views/dogs/_form.html.erb
<%= form_with(model: dog) do |form| %>
  <% if dog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
        <% dog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :breed, style: "display: block" %>
    <%= form.text_field :breed %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :image_url, style: "display: block" %>
    <%= form.text_field :image_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<% content_for :title, "Editing dog" %>

<h1>Editing dog</h1>

<%= render "form", dog: @dog %>

<br>

<div>
  <%= link_to "Show this dog", @dog %> |
  <%= link_to "Back to dogs", dogs_path %>
</div>

app/views/dogs/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Dogs" %>

<h1>Dogs</h1>

<div id="dogs">
  <% @dogs.each do |dog| %>
    <%= render dog %>
    <p>
      <%= link_to "Show this dog", dog %>
    </p>
  <% end %>
</div>

<%= link_to "New dog", new_dog_path %>

app/views/dogs/new.html.erb
<% content_for :title, "New dog" %>

<h1>New dog</h1>

<%= render "form", dog: @dog %>

<br>

<div>
  <%= link_to "Back to dogs", dogs_path %>
</div>

app/views/dogs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dog %>

<div>
  <%= link_to "Edit this dog", edit_dog_path(@dog) %> |
  <%= link_to "Back to dogs", dogs_path %>

  <%= button_to "Destroy this dog", @dog, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Pet Store" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>